name: Memo CI

on: # 监听master分支上的push事件
  push:
    branches:
      - master

jobs:
  # 发布到服务器
  build-and-deploy-to-server:
    runs-on: ubuntn-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: FE Install Dependencies and Build Project
        run: |
          cd frontend
          npm install
          npm run build

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.2
        env:
          SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
          ARGS: '-avz --delete'
          SOURCE: 'dist/'
          REMOTE_HOST: ${{secrets.REMOTE_HOST}}
          REMOTE_USER: ${{secrets.REMOTE_USER}}
          TARGET: ${{secrets.REMOTE_TARGET}}

